### ISSUE TITLE
Error in init_obj(obj) in Tutorial

### ISSUE THREAD

**Issue by yuxi-Zhao** [ZJUFanLab/scRank#5]
As described in the title, is it a custom function？I‘m a beginner in single-cell analysis, not familiar with these data format processing.

**Comment by mianaz** [comment]
I believe this is a typo in the tutorial. init_obj(obj) should in fact be init_mod(obj)

**Comment by yuxi-Zhao** [comment]
> I believe this is a typo in the tutorial. init_obj(obj) should in fact be init_mod(obj)
Thats right, thanks~

**Comment by Lee0498** [comment]
Hi, @mianaz, thank you for pointing out this typo in the tutorial！
The issue with the init_obj(obj) function name has been corrected to init_mod(obj) in the documentation. I appreciate your help in improving the tutorial. The issue is now resolved.
